### PR TITLE
[ERD] Add ERD

### PR DESCRIPTION
**Pull request by yorkittran**
# Create ERD with Navicat
This is an ERD for project training step 2
erd

### CODE REVIEW

**Comment by khanhnd90** [comment]
Database normalization is good 👍 
But you miss some informations. 
- When a user create a products, we should save who created it, when it is created
- About memories table, IMO, we don't need column unit. convert amount to GB before save to database is better, it'll help you easier to sort by memory.
- About models table, `year_of_manufature` should not a `int`, better save datetime format (dd/mm/yyyy).   
- Where is `images` table? 
- For management purpose, you can use `staffs` instead of `users`.

Some questions:
- Why `products` instead of `phones` ? 
- If we want to sort by os version from newest to oldest, how do we can sort when version is string ?
- Should we create a relation between `body_color` and `model` ? e.g. the red of iphone 11 is different with the red of samsung galaxy. If this's too complicated, we could skip 😄 
- Could staff edit/update or delete a products? 

Rails support almost columns types : https://fullstackheroes.com/rails/column-types/

**Comment by yorkittran** [comment]
@khanhnd90 san, I've updated my ERD like this
erd

**Review by khanhnd90 — APPROVED** [review]
LGTM 🍿 
@raksul-sian-izm  plz help me review this when you have time

**Comment by raksul-sian-izm** [comment]
Reviewed.

- Define not null/nullable constraint
- Confirm ERD mark meaning and update if necessary
- Define index

**Comment by yorkittran** [comment]
@raksul-sian-izm san plz review my latest ERD if you have time. In this ERD, I edit some of tables like:

- Define not nullable for foreign keys
- Define index for **models**->name
I don't define indexes on **phones** cause my search engine only search based on model's name. When I need to find phones, I will search on relative tables first then use these id to get the phone. Ex: I'll find out if "Space Grey" is exist on **body_colors** or not, then get its id and search on **phones** so **phones** just have some indexes in foreign keys, no need to have a composite index.

erd

**Comment by raksul-sian-izm** [comment]
LGTM 🍭

**Pull request merged**
