### PR TITLE
[Wireframes] Update some wireframes

### PR DESCRIPTION
**Pull request by yorkittran**
# Home
- Search with inventory's model name
- Replace dropdown with filter
- Add sort by price
Home

# Dashboard
- Search with all fields in inventory
- Add show entries per page
- Add sorter in every column
Dashboard

# Create/Edit
- Add input for missing fields
Create:Edit

# Sign up
User who sign up will act with 'user' role. Only user who has 'manager' role can change other user's role

### CODE REVIEW

**Review by khanhnd90 — APPROVED** [review]
LGTM 🍿 pop

**Comment by NhanHo** [comment]
One of the main reason for the wireframe section of the exercise is to think about what the user workflow is while using our application and he necessary technical decisions we need to make for them to accomplish their goal. Let's first focus on the manager and their workflow.

For a manager, their usage of the "registering their inventory" would necessary be different than let's say someone registering an item for their art collections. Specifically, the manager would need to add a large number of items (otherwise there wouldn't be much of an inventory!). This means the speed they can register an item will matter a lot, and having them type in every single attributes of the devices is very time consuming. Additionally, how would we deal with typo and mismatched data when inputting? Do you think your current design will facilitate the workflow, or is there any adjustment you can think of?

For "listing of inventory", an art collector might want to view their item one by one, but what kind of information or task does a store manager want when viewing their inventory? And how does your design fit in with the usage?

**Comment by yorkittran** [comment]
> For a manager, their usage of the "registering their inventory" would necessary be different than let's say someone registering an item for their art collections. Specifically, the manager would need to add a large number of items (otherwise there wouldn't be much of an inventory!). This means the speed they can register an item will matter a lot, and having them type in every single attributes of the devices is very time consuming. Additionally, how would we deal with typo and mismatched data when inputting? Do you think your current design will facilitate the workflow, or is there any adjustment you can think of?

In this situation, I think I should make a tab by side of create inventory call "bulk create inventory" to help manager upload a number of inventory. Manager will upload a CSV file with data but I have a little problem with images. I'm finding the best solution for this.

> For "listing of inventory", an art collector might want to view their item one by one, but what kind of information or task does a store manager want when viewing their inventory? And how does your design fit in with the usage?

In my opinion, manager should be able to view all the fields in inventory to check if there was any data wrong or not. The fields are not too many so it can be look good in the table.
Thank you @NhanHo san, and I may need to ask you about some solutions with upload multiple images.

**Comment by yorkittran** [comment]
@NhanHo, @khanhnd90 if you have time, please help me by reviewing these new wireframes

**Review by khanhnd90 — APPROVED** [review]
LGTM 👍

**Pull request merged**
